---


- name: add apt key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present
  when: ansible_os_family == "Debian"


- name: install required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - openjdk-8-jre-headless
    - uuid-runtime
    - pwgen
  when: ansible_os_family == "Debian"


- name: add repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
    state: present
  when: ansible_os_family == "Debian"


- name: install elasticsearch
  apt:
    name: elasticsearch
    state: present
  when: ansible_os_family == "Debian"
